/*
GenerateSUnitEquationsErrors.m

Author: Adela Gherga <adelagherga@gmail.com>
Copyright © 2021, Adela Gherga, all rights reserved.
Created:  1 February 2021

Description: Compilation of several internatl errors generated by Magma when running
             GenerateSUnitEq.m. This code has been emailed to Magma, and is not to be run.

Commentary:  N/A

To do list:  N/A

Example:     N/A

*/

clist:= [2,9,24,175];
n:=3;
QUV<U,V>:=PolynomialRing(Rationals(),2);
Zx_<x_>:= PolynomialRing(Integers());
F:=&+[clist[i+1]*U^(n-i)*V^i : i in [0..n]];
ThueF:= Thue(Evaluate(F,[x_,1])); // generate Thue equation
i:= 11;
Solutions(ThueF,i);


Magma: Internal error

Please mail this entire run [*** WITH THE DETAILS BELOW ***]
    to magma-bugs@maths.usyd.edu.au

You can print the entire input by entering:
%P

Version: 2.25-7
Machine type: intel64-linux
Initial seed: 1529052476
Time to this point: 3.46
Memory usage: 32.09MB
Segmentation fault

//------------------------------------------------------------------------------------------//


clist:= [ 7, 21, 18, 64 ];
i:=37;
QUV<U,V>:=PolynomialRing(Rationals(),2);
Qx<x>:= PolynomialRing(Rationals());
Zx_<x_>:= PolynomialRing(Integers());
n:=3;
F:=&+[clist[i+1]*U^(n-i)*V^i : i in [0..n]];
ThueF:= Thue(Evaluate(F,[x_,1])); // generate Thue equation
Solutions(ThueF,i);


Magma: Internal error

Please mail this entire run [*** WITH THE DETAILS BELOW ***]
    to magma-bugs@maths.usyd.edu.au

You can print the entire input by entering:
%P

Version: 2.25-7
Machine type: intel64-linux
Initial seed: 2665918998
Time to this point: 3.59
Memory usage: 32.09MB
Segmentation fault

//------------------------------------------------------------------------------------------//

clist:= [12,25,34,39];
n:=3;
i:= 2;
QUV<U,V>:=PolynomialRing(Rationals(),2);
Zx_<x_>:= PolynomialRing(Integers());
F:=&+[clist[i+1]*U^(n-i)*V^i : i in [0..n]];
ThueF:= Thue(Evaluate(F,[x_,1])); // generate Thue equation
Solutions(ThueF,i);


Magma: Internal error

Please mail this entire run [*** WITH THE DETAILS BELOW ***]
    to magma-bugs@maths.usyd.edu.au

You can print the entire input by entering:
%P

Version: 2.25-7
Machine type: intel64-linux
Initial seed: 743702896
Time to this point: 3.75
Memory usage: 32.09MB
Segmentation fault

//---------------------------------------------------------

clist:= [9,16,31,42];
n:=3;
QUV<U,V>:=PolynomialRing(Rationals(),2);
Zx_<x_>:= PolynomialRing(Integers());
F:=&+[clist[i+1]*U^(n-i)*V^i : i in [0..n]];
ThueF:= Thue(Evaluate(F,[x_,1])); // generate Thue equation
i:= 3;
Solutions(ThueF,i);


Magma: Internal error

Please mail this entire run [*** WITH THE DETAILS BELOW ***]
    to magma-bugs@maths.usyd.edu.au

You can print the entire input by entering:
%P

Version: 2.25-7
Machine type: intel64-linux
Initial seed: 1111125234
Time to this point: 3.6
Memory usage: 32.09MB
Segmentation fault
